export {default as IconPlay} from "./IconPlay"
export {default as IconExplore} from "./IconExprore"
export {default as IconStudy} from "./IconStudy"
export {default as IconComment} from "./IconComment"
export {default as IconEye} from "./IconEye"
export {default as IconUser} from "./IconUser"
export {default as IconOrder} from "./IconOrder"
export {default as IconStar} from "./IconStar"